/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps } from 'restful-react';

import * as RestfulShesha from '../utils/fetchers';
export const SPEC_VERSION = 'v1';
export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

/**
 * Generic DTO of the simple autocomplete item
 */
export interface AutocompleteItemDto {
  value?: string | null;
  displayText?: string | null;
}

export interface AutocompleteItemDtoListAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: AutocompleteItemDto[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ApiEndpointsQueryParams {
  term?: string;
  verb?: string;
  maxResultCount?: number;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type ApiEndpointsProps = Omit<
  GetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, ApiEndpointsQueryParams, void>,
  'path'
>;

export const ApiEndpoints = (props: ApiEndpointsProps) => (
  <Get<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, ApiEndpointsQueryParams, void>
    path={`/api/services/app/Api/Endpoints`}
    {...props}
  />
);

export type UseApiEndpointsProps = Omit<
  UseGetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, ApiEndpointsQueryParams, void>,
  'path'
>;

export const useApiEndpoints = (props: UseApiEndpointsProps) =>
  useGet<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, ApiEndpointsQueryParams, void>(
    `/api/services/app/Api/Endpoints`,
    props
  );

export type apiEndpointsProps = Omit<
  RestfulShesha.GetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, ApiEndpointsQueryParams, void>,
  'queryParams'
>;
export const apiEndpoints = (queryParams: ApiEndpointsQueryParams, props: apiEndpointsProps) =>
  RestfulShesha.get<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, ApiEndpointsQueryParams, void>(
    `/api/services/app/Api/Endpoints`,
    queryParams,
    props
  );
