/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps } from 'restful-react';

import * as RestfulShesha from '../utils/fetchers';
export const SPEC_VERSION = 'v1';
/**
 * Generic DTO of the simple autocomplete item
 */
export interface AutocompleteItemDto {
  value?: string | null;
  displayText?: string | null;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface AutocompleteItemDtoListAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: AutocompleteItemDto[] | null;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface AutocompleteListQueryParams {
  term?: string | null;
  typeShortAlias?: string | null;
  allowInherited?: boolean;
  selectedValue?: string | null;
}

export type AutocompleteListProps = Omit<
  GetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, AutocompleteListQueryParams, void>,
  'path'
>;

/**
 * Get autocomplete list
 */
export const AutocompleteList = (props: AutocompleteListProps) => (
  <Get<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, AutocompleteListQueryParams, void>
    path={`/api/Autocomplete/List`}
    {...props}
  />
);

export type UseAutocompleteListProps = Omit<
  UseGetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, AutocompleteListQueryParams, void>,
  'path'
>;

/**
 * Get autocomplete list
 */
export const useAutocompleteList = (props: UseAutocompleteListProps) =>
  useGet<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, AutocompleteListQueryParams, void>(
    `/api/Autocomplete/List`,
    props
  );

export type autocompleteListProps = Omit<
  RestfulShesha.GetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, AutocompleteListQueryParams, void>,
  'queryParams'
>;
/**
 * Get autocomplete list
 */
export const autocompleteList = (queryParams: AutocompleteListQueryParams, props: autocompleteListProps) =>
  RestfulShesha.get<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, AutocompleteListQueryParams, void>(
    `/api/Autocomplete/List`,
    queryParams,
    props
  );
