/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';

import * as RestfulShesha from '../utils/fetchers';
export const SPEC_VERSION = 'v1';
export interface AuthenticateModel {
  userNameOrEmailAddress: string;
  password: string;
  /**
   * Optional IMEI number. Is used for mobile applications
   */
  imei?: string | null;
}

export interface AuthenticateResultModel {
  accessToken?: string | null;
  encryptedAccessToken?: string | null;
  expireInSeconds?: number;
  expireOn?: string;
  userId?: number;
  personId?: string | null;
  deviceName?: string | null;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface AuthenticateResultModelAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: AuthenticateResultModel;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface BooleanAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: boolean;
}

export interface ExternalLoginProviderInfoModel {
  name?: string | null;
  clientId?: string | null;
}

export interface ExternalLoginProviderInfoModelListAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: ExternalLoginProviderInfoModel[] | null;
}

export interface ExternalAuthenticateModel {
  authProvider: string;
  providerKey: string;
  providerAccessCode: string;
}

export interface ExternalAuthenticateResultModel {
  accessToken?: string | null;
  encryptedAccessToken?: string | null;
  expireInSeconds?: number;
  waitingForActivation?: boolean;
}

export interface ExternalAuthenticateResultModelAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: ExternalAuthenticateResultModel;
}

export type TokenAuthAuthenticateProps = Omit<
  MutateProps<AuthenticateResultModelAjaxResponse, AjaxResponseBase, void, AuthenticateModel, void>,
  'path' | 'verb'
>;

export const TokenAuthAuthenticate = (props: TokenAuthAuthenticateProps) => (
  <Mutate<AuthenticateResultModelAjaxResponse, AjaxResponseBase, void, AuthenticateModel, void>
    verb="POST"
    path={`/api/TokenAuth/Authenticate`}
    {...props}
  />
);

export type UseTokenAuthAuthenticateProps = Omit<
  UseMutateProps<AuthenticateResultModelAjaxResponse, AjaxResponseBase, void, AuthenticateModel, void>,
  'path' | 'verb'
>;

export const useTokenAuthAuthenticate = (props: UseTokenAuthAuthenticateProps) =>
  useMutate<AuthenticateResultModelAjaxResponse, AjaxResponseBase, void, AuthenticateModel, void>(
    'POST',
    `/api/TokenAuth/Authenticate`,
    props
  );

export type tokenAuthAuthenticateProps = Omit<
  RestfulShesha.MutateProps<AuthenticateResultModelAjaxResponse, AjaxResponseBase, void, AuthenticateModel, void>,
  'data'
>;
export const tokenAuthAuthenticate = (data: AuthenticateModel, props: tokenAuthAuthenticateProps) =>
  RestfulShesha.mutate<AuthenticateResultModelAjaxResponse, AjaxResponseBase, void, AuthenticateModel, void>(
    'POST',
    `/api/TokenAuth/Authenticate`,
    data,
    props
  );

export type TokenAuthSignOffProps = Omit<
  MutateProps<BooleanAjaxResponse, AjaxResponseBase, void, void, void>,
  'path' | 'verb'
>;

export const TokenAuthSignOff = (props: TokenAuthSignOffProps) => (
  <Mutate<BooleanAjaxResponse, AjaxResponseBase, void, void, void>
    verb="POST"
    path={`/api/TokenAuth/SignOff`}
    {...props}
  />
);

export type UseTokenAuthSignOffProps = Omit<
  UseMutateProps<BooleanAjaxResponse, AjaxResponseBase, void, void, void>,
  'path' | 'verb'
>;

export const useTokenAuthSignOff = (props: UseTokenAuthSignOffProps) =>
  useMutate<BooleanAjaxResponse, AjaxResponseBase, void, void, void>('POST', `/api/TokenAuth/SignOff`, props);

export type tokenAuthSignOffProps = Omit<
  RestfulShesha.MutateProps<BooleanAjaxResponse, AjaxResponseBase, void, void, void>,
  'data'
>;
export const tokenAuthSignOff = (props: tokenAuthSignOffProps) =>
  RestfulShesha.mutate<BooleanAjaxResponse, AjaxResponseBase, void, void, void>(
    'POST',
    `/api/TokenAuth/SignOff`,
    undefined,
    props
  );

export type TokenAuthGetExternalAuthenticationProvidersProps = Omit<
  GetProps<ExternalLoginProviderInfoModelListAjaxResponse, AjaxResponseBase, void, void>,
  'path'
>;

export const TokenAuthGetExternalAuthenticationProviders = (
  props: TokenAuthGetExternalAuthenticationProvidersProps
) => (
  <Get<ExternalLoginProviderInfoModelListAjaxResponse, AjaxResponseBase, void, void>
    path={`/api/TokenAuth/GetExternalAuthenticationProviders`}
    {...props}
  />
);

export type UseTokenAuthGetExternalAuthenticationProvidersProps = Omit<
  UseGetProps<ExternalLoginProviderInfoModelListAjaxResponse, AjaxResponseBase, void, void>,
  'path'
>;

export const useTokenAuthGetExternalAuthenticationProviders = (
  props: UseTokenAuthGetExternalAuthenticationProvidersProps
) =>
  useGet<ExternalLoginProviderInfoModelListAjaxResponse, AjaxResponseBase, void, void>(
    `/api/TokenAuth/GetExternalAuthenticationProviders`,
    props
  );

export type tokenAuthGetExternalAuthenticationProvidersProps = Omit<
  RestfulShesha.GetProps<ExternalLoginProviderInfoModelListAjaxResponse, AjaxResponseBase, void, void>,
  'queryParams'
>;
export const tokenAuthGetExternalAuthenticationProviders = (props: tokenAuthGetExternalAuthenticationProvidersProps) =>
  RestfulShesha.get<ExternalLoginProviderInfoModelListAjaxResponse, AjaxResponseBase, void, void>(
    `/api/TokenAuth/GetExternalAuthenticationProviders`,
    undefined,
    props
  );

export type TokenAuthExternalAuthenticateProps = Omit<
  MutateProps<ExternalAuthenticateResultModelAjaxResponse, AjaxResponseBase, void, ExternalAuthenticateModel, void>,
  'path' | 'verb'
>;

export const TokenAuthExternalAuthenticate = (props: TokenAuthExternalAuthenticateProps) => (
  <Mutate<ExternalAuthenticateResultModelAjaxResponse, AjaxResponseBase, void, ExternalAuthenticateModel, void>
    verb="POST"
    path={`/api/TokenAuth/ExternalAuthenticate`}
    {...props}
  />
);

export type UseTokenAuthExternalAuthenticateProps = Omit<
  UseMutateProps<ExternalAuthenticateResultModelAjaxResponse, AjaxResponseBase, void, ExternalAuthenticateModel, void>,
  'path' | 'verb'
>;

export const useTokenAuthExternalAuthenticate = (props: UseTokenAuthExternalAuthenticateProps) =>
  useMutate<ExternalAuthenticateResultModelAjaxResponse, AjaxResponseBase, void, ExternalAuthenticateModel, void>(
    'POST',
    `/api/TokenAuth/ExternalAuthenticate`,
    props
  );

export type tokenAuthExternalAuthenticateProps = Omit<
  RestfulShesha.MutateProps<
    ExternalAuthenticateResultModelAjaxResponse,
    AjaxResponseBase,
    void,
    ExternalAuthenticateModel,
    void
  >,
  'data'
>;
export const tokenAuthExternalAuthenticate = (
  data: ExternalAuthenticateModel,
  props: tokenAuthExternalAuthenticateProps
) =>
  RestfulShesha.mutate<
    ExternalAuthenticateResultModelAjaxResponse,
    AjaxResponseBase,
    void,
    ExternalAuthenticateModel,
    void
  >('POST', `/api/TokenAuth/ExternalAuthenticate`, data, props);
