export const DataTypes = {
  guid: 'guid',
  string: 'string',
  number: 'number',
  date: 'date',
  time: 'time',
  dateTime: 'date-time',
  entityReference: 'entity',
  file: 'file',
  referenceListItem: 'reference-list-item',
  boolean: 'boolean',
  array: 'array',
  object: 'object',
  objectReference: 'object-reference',
  specification: 'specification',
  context: 'context',
  function: 'function',
  any: 'any',
};

export const StringFormats = {
  singleline: 'singleline',
  multiline: 'multiline',
  html: 'html',
  json: 'json',
  javascript: 'javascript',
  password: 'password',
  emailAddress: 'email',
  phoneNumber: 'phone',
  url: 'url',
};
