export const COUNTRY_CODES = [
  { label: 'Afghanistan', value: 'Afghanistan', code: 'af' },
  { label: 'Åland', value: 'Åland', code: 'ax' },
  { label: 'Albania', value: 'Albania', code: 'al' },
  { label: 'Algeria', value: 'Algeria', code: 'dz' },
  { label: 'American Samoa', value: 'American Samoa', code: 'as' },
  { label: 'Andorra', value: 'Andorra', code: 'ad' },
  { label: 'Angola', value: 'Angola', code: 'ao' },
  { label: 'Anguilla', value: 'Anguilla', code: 'ai' },
  { label: 'Antarctica', value: 'Antarctica', code: 'aq' },
  { label: 'Antigua and Barbuda', value: 'Antigua and Barbuda', code: 'ag' },
  { label: 'Argentina', value: 'Argentina', code: 'ar' },
  { label: 'Armenia', value: 'Armenia', code: 'am' },
  { label: 'Aruba', value: 'Aruba', code: 'aw' },
  { label: 'Ascension Island', value: 'Ascension Island', code: 'ac' },
  { label: 'Australia', value: 'Australia', code: 'au' },
  { label: 'Austria', value: 'Austria', code: 'at' },
  { label: 'Azerbaijan', value: 'Azerbaijan', code: 'az' },
  { label: 'Bahamas', value: 'Bahamas', code: 'bs' },
  { label: 'Bahrain', value: 'Bahrain', code: 'bh' },
  { label: 'Bangladesh', value: 'Bangladesh', code: 'bd' },
  { label: 'Barbados', value: 'Barbados', code: 'bb' },
  { label: 'Basque Country', value: 'Basque Country', code: 'eus' },
  { label: 'Belarus', value: 'Belarus', code: 'by' },
  { label: 'Belgium', value: 'Belgium', code: 'be' },
  { label: 'Belize', value: 'Belize', code: 'bz' },
  { label: 'Benin', value: 'Benin', code: 'bj' },
  { label: 'Bermuda', value: 'Bermuda', code: 'bm' },
  { label: 'Bhutan', value: 'Bhutan', code: 'bt' },
  { label: 'Bolivia', value: 'Bolivia', code: 'bo' },
  { label: 'Bonaire (Saba, Sint Eustatius)', value: 'Bonaire (Saba, Sint Eustatius)', code: 'bq' },
  { label: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina', code: 'ba' },
  { label: 'Botswana', value: 'Botswana', code: 'bw' },
  { label: 'Bouvet Island', value: 'Bouvet Island', code: 'bv' },
  { label: 'Brazil', value: 'Brazil', code: 'br' },
  { label: 'British Indian Ocean Territory', value: 'British Indian Ocean Territory', code: 'io' },
  { label: 'British Virgin Islands', value: 'British Virgin Islands', code: 'vg' },
  { label: 'Brunei', value: 'Brunei', code: 'bn' },
  { label: 'Bulgaria', value: 'Bulgaria', code: 'bg' },
  { label: 'Burkina Faso', value: 'Burkina Faso', code: 'bf' },
  { label: 'Burma (Myanmar)', value: 'Burma (Myanmar)', code: 'mm' },
  { label: 'Burundi', value: 'Burundi', code: 'bi' },
  { label: 'Cambodia', value: 'Cambodia', code: 'kh' },
  { label: 'Cameroon', value: 'Cameroon', code: 'cm' },
  { label: 'Canada', value: 'Canada', code: 'ca' },
  { label: 'Cape Verde (in Portuguese: Cabo Verde)', value: 'Cape Verde (in Portuguese: Cabo Verde)', code: 'cv' },
  { label: 'Catalonia', value: 'Catalonia', code: 'cat' },
  { label: 'Cayman Islands', value: 'Cayman Islands', code: 'ky' },
  { label: 'Central African Republic', value: 'Central African Republic', code: 'cf' },
  { label: 'Chad', value: 'Chad', code: 'td' },
  { label: 'Chile', value: 'Chile', code: 'cl' },
  { label: "China, People's Republic of", value: "China, People's Republic of", code: 'cn' },
  { label: 'Christmas Island', value: 'Christmas Island', code: 'cx' },
  { label: 'Cocos (Keeling) Islands', value: 'Cocos (Keeling) Islands', code: 'cc' },
  { label: 'Colombia', value: 'Colombia', code: 'co' },
  { label: 'Comoros', value: 'Comoros', code: 'km' },
  { label: 'Congo, Democratic Republic of the (Congo-Kinshasa)', value: 'Congo, Democratic Republic of the (Congo-Kinshasa)', code: 'cd' },
  { label: 'Congo, Republic of the (Congo-Brazzaville)', value: 'Congo, Republic of the (Congo-Brazzaville)', code: 'cg' },
  { label: 'Cook Islands', value: 'Cook Islands', code: 'ck' },
  { label: 'Costa Rica', value: 'Costa Rica', code: 'cr' },
  { label: "Côte d'Ivoire (Ivory Coast)", value: "Côte d'Ivoire (Ivory Coast)", code: 'ci' },
  { label: 'Croatia', value: 'Croatia', code: 'hr' },
  { label: 'Cuba', value: 'Cuba', code: 'cu' },
  { label: 'Curaçao', value: 'Curaçao', code: 'cw' },
  { label: 'Cyprus', value: 'Cyprus', code: 'cy' },
  { label: 'Czechia (Czech Republic)', value: 'Czechia (Czech Republic)', code: 'cz' },
  { label: 'Denmark', value: 'Denmark', code: 'dk' },
  { label: 'Djibouti', value: 'Djibouti', code: 'dj' },
  { label: 'Dominica', value: 'Dominica', code: 'dm' },
  { label: 'Dominican Republic', value: 'Dominican Republic', code: 'do' },
  { label: 'East Timor (Timor-Leste)', value: 'East Timor (Timor-Leste)', code: 'tl' },
  { label: 'Ecuador', value: 'Ecuador', code: 'ec' },
  { label: 'Egypt', value: 'Egypt', code: 'eg' },
  { label: 'El Salvador', value: 'El Salvador', code: 'sv' },
  { label: 'Equatorial Guinea', value: 'Equatorial Guinea', code: 'gq' },
  { label: 'Eritrea', value: 'Eritrea', code: 'er' },
  { label: 'Estonia', value: 'Estonia', code: 'ee' },
  { label: 'Ethiopia', value: 'Ethiopia', code: 'et' },
  { label: 'European Union', value: 'European Union', code: 'eu' },
  { label: 'Falkland Islands', value: 'Falkland Islands', code: 'fk' },
  { label: 'Faeroe Islands', value: 'Faeroe Islands', code: 'fo' },
  { label: 'Federated States of Micronesia', value: 'Federated States of Micronesia', code: 'fm' },
  { label: 'Fiji', value: 'Fiji', code: 'fj' },
  { label: 'Finland', value: 'Finland', code: 'fi' },
  { label: 'France', value: 'France', code: 'fr' },
  { label: 'French Guiana', value: 'French Guiana', code: 'gf' },
  { label: 'French Polynesia', value: 'French Polynesia', code: 'pf' },
  { label: 'French Southern and Antarctic Lands', value: 'French Southern and Antarctic Lands', code: 'tf' },
  { label: 'Gabon (officially: Gabonese Republic)', value: 'Gabon (officially: Gabonese Republic)', code: 'ga' },
  { label: 'Galicia', value: 'Galicia', code: 'gal' },
  { label: 'Gambia', value: 'Gambia', code: 'gm' },
  { label: 'Gaza Strip (Gaza, Palestine)', value: 'Gaza Strip (Gaza, Palestine)', code: 'ps' },
  { label: 'Georgia', value: 'Georgia', code: 'ge' },
  { label: 'Germany', value: 'Germany', code: 'de' },
  { label: 'Ghana', value: 'Ghana', code: 'gh' },
  { label: 'Gibraltar', value: 'Gibraltar', code: 'gi' },
  { label: 'Greece', value: 'Greece', code: 'gr' },
  { label: 'Greenland', value: 'Greenland', code: 'gl' },
  { label: 'Grenada', value: 'Grenada', code: 'gd' },
  { label: 'Guadeloupe', value: 'Guadeloupe', code: 'gp' },
  { label: 'Guam', value: 'Guam', code: 'gu' },
  { label: 'Guatemala', value: 'Guatemala', code: 'gt' },
  { label: 'Guernsey', value: 'Guernsey', code: 'gg' },
  { label: 'Guinea', value: 'Guinea', code: 'gn' },
  { label: 'Guinea-Bissau', value: 'Guinea-Bissau', code: 'gw' },
  { label: 'Guyana', value: 'Guyana', code: 'gy' },
  { label: 'Haiti', value: 'Haiti', code: 'ht' },
  { label: 'Heard Island and McDonald Islands', value: 'Heard Island and McDonald Islands', code: 'hm' },
  { label: 'Honduras', value: 'Honduras', code: 'hn' },
  { label: 'Hong Kong', value: 'Hong Kong', code: 'hk' },
  { label: 'Hungary', value: 'Hungary', code: 'hu' },
  { label: 'Iceland', value: 'Iceland', code: 'is' },
  { label: 'India', value: 'India', code: 'in' },
  { label: 'Indonesia', value: 'Indonesia', code: 'id' },
  { label: 'Iran', value: 'Iran', code: 'ir' },
  { label: 'Iraq', value: 'Iraq', code: 'iq' },
  { label: 'Ireland', value: 'Ireland', code: 'ie' },
  { label: 'Isle of Man', value: 'Isle of Man', code: 'im' },
  { label: 'Israel', value: 'Israel', code: 'il' },
  { label: 'Italy', value: 'Italy', code: 'it' },
  { label: 'Jamaica', value: 'Jamaica', code: 'jm' },
  { label: 'Japan', value: 'Japan', code: 'jp' },
  { label: 'Jersey', value: 'Jersey', code: 'je' },
  { label: 'Jordan', value: 'Jordan', code: 'jo' },
  { label: 'Kazakhstan', value: 'Kazakhstan', code: 'kz' },
  { label: 'Kenya', value: 'Kenya', code: 'ke' },
  { label: 'Kiribati', value: 'Kiribati', code: 'ki' },
  { label: 'Kuwait', value: 'Kuwait', code: 'kw' },
  { label: 'Kyrgyzstan', value: 'Kyrgyzstan', code: 'kg' },
  { label: 'Laos', value: 'Laos', code: 'la' },
  { label: 'Latvia', value: 'Latvia', code: 'lv' },
  { label: 'Lebanon', value: 'Lebanon', code: 'lb' },
  { label: 'Lesotho', value: 'Lesotho', code: 'ls' },
  { label: 'Liberia', value: 'Liberia', code: 'lr' },
  { label: 'Libya', value: 'Libya', code: 'ly' },
  { label: 'Liechtenstein', value: 'Liechtenstein', code: 'li' },
  { label: 'Lithuania', value: 'Lithuania', code: 'lt' },
  { label: 'Luxembourg', value: 'Luxembourg', code: 'lu' },
  { label: 'Macau', value: 'Macau', code: 'mo' },
  { label: 'Macedonia, Republic of (the former Yugoslav Republic of Macedonia, FYROM)', value: 'Macedonia, Republic of (the former Yugoslav Republic of Macedonia, FYROM)', code: 'mk' },
  { label: 'Madagascar', value: 'Madagascar', code: 'mg' },
  { label: 'Malawi', value: 'Malawi', code: 'mw' },
  { label: 'Malaysia', value: 'Malaysia', code: 'my' },
  { label: 'Maldives', value: 'Maldives', code: 'mv' },
  { label: 'Mali', value: 'Mali', code: 'ml' },
  { label: 'Malta', value: 'Malta', code: 'mt' },
  { label: 'Marshall Islands', value: 'Marshall Islands', code: 'mh' },
  { label: 'Martinique', value: 'Martinique', code: 'mq' },
  { label: 'Mauritania', value: 'Mauritania', code: 'mr' },
  { label: 'Mauritius', value: 'Mauritius', code: 'mu' },
  { label: 'Mayotte', value: 'Mayotte', code: 'yt' },
  { label: 'Mexico', value: 'Mexico', code: 'mx' },
  { label: 'Moldova', value: 'Moldova', code: 'md' },
  { label: 'Monaco', value: 'Monaco', code: 'mc' },
  { label: 'Mongolia', value: 'Mongolia', code: 'mn' },
  { label: 'Montenegro', value: 'Montenegro', code: 'me' },
  { label: 'Montserrat', value: 'Montserrat', code: 'ms' },
  { label: 'Morocco', value: 'Morocco', code: 'ma' },
  { label: 'Mozambique', value: 'Mozambique', code: 'mz' },
  { label: 'Namibia', value: 'Namibia', code: 'na' },
  { label: 'Nauru', value: 'Nauru', code: 'nr' },
  { label: 'Nepal', value: 'Nepal', code: 'np' },
  { label: 'Netherlands', value: 'Netherlands', code: 'nl' },
  { label: 'New Caledonia', value: 'New Caledonia', code: 'nc' },
  { label: 'New Zealand', value: 'New Zealand', code: 'nz' },
  { label: 'Nicaragua', value: 'Nicaragua', code: 'ni' },
  { label: 'Niger', value: 'Niger', code: 'ne' },
  { label: 'Nigeria', value: 'Nigeria', code: 'ng' },
  { label: 'Niue', value: 'Niue', code: 'nu' },
  { label: 'Norfolk Island', value: 'Norfolk Island', code: 'nf' },
  { label: 'North Cyprus (unrecognised, self-declared state)', value: 'North Cyprus (unrecognised, self-declared state)', code: 'ct' },
  { label: 'North Korea', value: 'North Korea', code: 'kp' },
  { label: 'Northern Mariana Islands', value: 'Northern Mariana Islands', code: 'mp' },
  { label: 'Norway', value: 'Norway', code: 'no' },
  { label: 'Oman', value: 'Oman', code: 'om' },
  { label: 'Pakistan', value: 'Pakistan', code: 'pk' },
  { label: 'Palau', value: 'Palau', code: 'pw' },
  { label: 'Panama', value: 'Panama', code: 'pa' },
  { label: 'Papua New Guinea', value: 'Papua New Guinea', code: 'pg' },
  { label: 'Paraguay', value: 'Paraguay', code: 'py' },
  { label: 'Peru', value: 'Peru', code: 'pe' },
  { label: 'Philippines', value: 'Philippines', code: 'ph' },
  { label: 'Pitcairn Islands', value: 'Pitcairn Islands', code: 'pn' },
  { label: 'Poland', value: 'Poland', code: 'pl' },
  { label: 'Portugal', value: 'Portugal', code: 'pt' },
  { label: 'Puerto Rico', value: 'Puerto Rico', code: 'pr' },
  { label: 'Qatar', value: 'Qatar', code: 'qa' },
  { label: 'Romania', value: 'Romania', code: 'ro' },
  { label: 'Russia', value: 'Russia', code: 'ru' },
  { label: 'Rwanda', value: 'Rwanda', code: 'rw' },
  { label: 'Réunion Island', value: 'Réunion Island', code: 're' },
  { label: 'Saint Barthélemy', value: 'Saint Barthélemy', code: 'bl' },
  { label: 'Saint Helena', value: 'Saint Helena', code: 'sh' },
  { label: 'Saint Kitts and Nevis', value: 'Saint Kitts and Nevis', code: 'kn' },
  { label: 'Saint Lucia', value: 'Saint Lucia', code: 'lc' },
  { label: 'Saint Martin', value: 'Saint Martin', code: 'mf' },
  { label: 'Saint-Pierre and Miquelon', value: 'Saint-Pierre and Miquelon', code: 'pm' },
  { label: 'Saint Vincent and the Grenadines', value: 'Saint Vincent and the Grenadines', code: 'vc' },
  { label: 'Samoa', value: 'Samoa', code: 'ws' },
  { label: 'San Marino', value: 'San Marino', code: 'sm' },
  { label: 'São Tomé and Príncipe', value: 'São Tomé and Príncipe', code: 'st' },
  { label: 'Saudi Arabia', value: 'Saudi Arabia', code: 'sa' },
  { label: 'Senegal', value: 'Senegal', code: 'sn' },
  { label: 'Serbia', value: 'Serbia', code: 'rs' },
  { label: 'Seychelles', value: 'Seychelles', code: 'sc' },
  { label: 'Sierra Leone', value: 'Sierra Leone', code: 'sl' },
  { label: 'Singapore', value: 'Singapore', code: 'sg' },
  { label: 'Sint Maarten', value: 'Sint Maarten', code: 'sx' },
  { label: 'Slovakia', value: 'Slovakia', code: 'sk' },
  { label: 'Slovenia', value: 'Slovenia', code: 'si' },
  { label: 'Solomon Islands', value: 'Solomon Islands', code: 'sb' },
  { label: 'Somalia (Somaliland)', value: 'Somalia (Somaliland)', code: 'so' },
  { label: 'South Africa', value: 'South Africa', code: 'za' },
  { label: 'South Georgia and the South Sandwich Islands', value: 'South Georgia and the South Sandwich Islands', code: 'gs' },
  { label: 'South Korea', value: 'South Korea', code: 'kr' },
  { label: 'South Sudan', value: 'South Sudan', code: 'ss' },
  { label: 'Spain', value: 'Spain', code: 'es' },
  { label: 'Sri Lanka', value: 'Sri Lanka', code: 'lk' },
  { label: 'Sudan', value: 'Sudan', code: 'sd' },
  { label: 'Suriname', value: 'Suriname', code: 'sr' },
  { label: 'Svalbard and Jan Mayen Islands', value: 'Svalbard and Jan Mayen Islands', code: 'sj' },
  { label: 'Swaziland', value: 'Swaziland', code: 'sz' },
  { label: 'Sweden', value: 'Sweden', code: 'se' },
  { label: 'Switzerland', value: 'Switzerland', code: 'ch' },
  { label: 'Syria', value: 'Syria', code: 'sy' },
  { label: 'Taiwan', value: 'Taiwan', code: 'tw' },
  { label: 'Tajikistan', value: 'Tajikistan', code: 'tj' },
  { label: 'Tanzania', value: 'Tanzania', code: 'tz' },
  { label: 'Thailand', value: 'Thailand', code: 'th' },
  { label: 'Togo', value: 'Togo', code: 'tg' },
  { label: 'Tokelau', value: 'Tokelau', code: 'tk' },
  { label: 'Tonga', value: 'Tonga', code: 'to' },
  { label: 'Trinidad & Tobago', value: 'Trinidad & Tobago', code: 'tt' },
  { label: 'Tunisia', value: 'Tunisia', code: 'tn' },
  { label: 'Turkey', value: 'Turkey', code: 'tr' },
  { label: 'Turkmenistan', value: 'Turkmenistan', code: 'tm' },
  { label: 'Turks and Caicos Islands', value: 'Turks and Caicos Islands', code: 'tc' },
  { label: 'Tuvalu', value: 'Tuvalu', code: 'tv' },
  { label: 'Uganda', value: 'Uganda', code: 'ug' },
  { label: 'Ukraine', value: 'Ukraine', code: 'ua' },
  { label: 'United Arab Emirates (UAE)', value: 'United Arab Emirates (UAE)', code: 'ae' },
  { label: 'United Kingdom (UK)', value: 'United Kingdom (UK)', code: 'uk' },
  { label: 'United States of America (USA)', value: 'United States of America (USA)', code: 'us' },
  { label: 'United States Virgin Islands', value: 'United States Virgin Islands', code: 'vi' },
  { label: 'Uruguay', value: 'Uruguay', code: 'uy' },
  { label: 'Uzbekistan', value: 'Uzbekistan', code: 'uz' },
  { label: 'Vanuatu', value: 'Vanuatu', code: 'vu' },
  { label: 'Vatican City', value: 'Vatican City', code: 'va' },
  { label: 'Venezuela', value: 'Venezuela', code: 've' },
  { label: 'Vietnam', value: 'Vietnam', code: 'vn' },
  { label: 'Wallis and Futuna', value: 'Wallis and Futuna', code: 'wf' },
  { label: 'Western Sahara', value: 'Western Sahara', code: 'eh' },
  { label: 'Yemen', value: 'Yemen', code: 'ye' },
  { label: 'Zambia', value: 'Zambia', code: 'zm' },
  { label: 'Zimbabwe', value: 'Zimbabwe', code: 'zw' },
];
