drop view IF EXISTS "vw_Core_WorkflowSentItems";
drop view IF EXISTS "vw_Core_WorkflowMyItems";
drop view IF EXISTS "vw_Core_WorkflowInboxItems";
drop view IF EXISTS "vw_Core_WorkflowDraftItems";
drop view IF EXISTS "vw_Core_WorkflowLogItems";
drop table if exists "Core_WorkflowTodoItems" cascade;
drop table if exists "Core_WorkflowMessages" cascade;
drop table if exists "Core_WorkflowHighLevelAssigneeDependencies" cascade;
drop table if exists "Core_WorkflowInstanceOwners" cascade;
drop table if exists "Core_WorkflowScheduledJobs" cascade;
drop table if exists "Core_WorkflowHighLevelAssignees" cascade;
drop table if exists "Core_WorkflowAssignees" cascade;
drop table if exists "Core_WorkflowExecutionLogItems" cascade;
drop table if exists "Core_WorkflowTasks" cascade;
drop table if exists "Core_WorkflowInstances" cascade;
drop table if exists "Core_ProcessableEntityDocuments" cascade;
drop table if exists "Core_ProcessConfigurationDocumentTemplates" cascade;
drop table if exists "Core_TestProcesses" cascade;
drop table if exists "Core_TestProcessConfigurations" cascade;
drop table if exists "Core_ProcessableEntities" cascade;
drop table if exists "Core_HumanActivityConfigurations" cascade;
drop table if exists "Core_ProcessConfigurations" cascade;
drop table if exists "Core_WorkflowDefinitions" cascade;
drop table if exists "Core_ConfigurableHumanActivities" cascade;