INSERT INTO frwk.entity_properties
           (id
           ,creation_time
           ,creator_user_id
           ,last_modification_time
           ,last_modifier_user_id
           ,is_deleted
           ,deletion_time
           ,deleter_user_id
           ,audited
           ,cascade_create
           ,cascade_delete_unreferenced
           ,cascade_update
           ,data_format
           ,data_type
           ,description
           ,entity_type
           ,is_framework_related
           ,label
           ,max
           ,max_length
           ,min
           ,min_length
           ,name
           ,read_only
           ,reference_list_module
           ,reference_list_name
           ,reg_exp
           ,required
           ,sort_order
           ,source_lkp
           ,suppress
           ,validation_message
           ,entity_config_revision_id
           ,items_type_id
           ,parent_property_id
           ,created_in_db
           ,column_name
           ,list_configuration
           ,formatting)
SELECT 
	"Id"
    ,"CreationTime"
    ,"CreatorUserId"
    ,"LastModificationTime"
    ,"LastModifierUserId"
    ,"IsDeleted"
    ,"DeletionTime"
    ,"DeleterUserId"
    ,"Audited"
	,"CascadeCreate"
    ,"CascadeDeleteUnreferenced"
	,"CascadeUpdate"
	,"DataFormat"
	,"DataType"
    ,"Description"
    ,"EntityType"
    ,"IsFrameworkRelated"
	,"Label"
	,"Max"
	,"MaxLength"
    ,"Min"
    ,"MinLength"
    ,"Name"
	,"ReadOnly"
	,"ReferenceListModule"
    ,"ReferenceListName"
	,"RegExp"
	,"Required"
	,"SortOrder"
    ,"SourceLkp"
	,"Suppress"
	,"ValidationMessage"
	,"EntityConfigId"
    ,"ItemsTypeId"
    ,"ParentPropertyId"
    ,"CreatedInDb"
    ,"ColumnName"
    ,"ListConfiguration"
    ,"Formatting"
FROM "Frwk_EntityProperties"