/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface LdapSettingsDto {
  isEnabled?: boolean;
  server?: string | null;
  port?: number;
  useSsl?: boolean;
  domain?: string | null;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface LdapSettingsDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: LdapSettingsDto;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface LdapUpdateSettingsQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type LdapUpdateSettingsProps = Omit<
  MutateProps<void, unknown, LdapUpdateSettingsQueryParams, LdapSettingsDto, void>,
  'path' | 'verb'
>;

export const LdapUpdateSettings = (props: LdapUpdateSettingsProps) => (
  <Mutate<void, unknown, LdapUpdateSettingsQueryParams, LdapSettingsDto, void>
    verb="PUT"
    path={`/api/services/SheshaLdap/Ldap/UpdateSettings`}
    {...props}
  />
);

export type UseLdapUpdateSettingsProps = Omit<
  UseMutateProps<void, unknown, LdapUpdateSettingsQueryParams, LdapSettingsDto, void>,
  'path' | 'verb'
>;

export const useLdapUpdateSettings = (props: UseLdapUpdateSettingsProps) =>
  useMutate<void, unknown, LdapUpdateSettingsQueryParams, LdapSettingsDto, void>(
    'PUT',
    `/api/services/SheshaLdap/Ldap/UpdateSettings`,
    props
  );

export interface LdapGetSettingsQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type LdapGetSettingsProps = Omit<
  GetProps<LdapSettingsDtoAjaxResponse, AjaxResponseBase, LdapGetSettingsQueryParams, void>,
  'path'
>;

export const LdapGetSettings = (props: LdapGetSettingsProps) => (
  <Get<LdapSettingsDtoAjaxResponse, AjaxResponseBase, LdapGetSettingsQueryParams, void>
    path={`/api/services/SheshaLdap/Ldap/GetSettings`}
    {...props}
  />
);

export type UseLdapGetSettingsProps = Omit<
  UseGetProps<LdapSettingsDtoAjaxResponse, AjaxResponseBase, LdapGetSettingsQueryParams, void>,
  'path'
>;

export const useLdapGetSettings = (props: UseLdapGetSettingsProps) =>
  useGet<LdapSettingsDtoAjaxResponse, AjaxResponseBase, LdapGetSettingsQueryParams, void>(
    `/api/services/SheshaLdap/Ldap/GetSettings`,
    props
  );
