/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export type OtpSendType = 1 | 2;

export interface SendPinInput {
  sendTo?: string | null;
  sendType: OtpSendType;
  recipientType?: string | null;
  recipientId?: string | null;
  lifetime?: number | null;
  actionType?: string | null;
}

export interface SendPinDto {
  operationId?: string;
  sentTo?: string | null;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface SendPinDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: SendPinDto;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface ResendPinInput {
  operationId: string;
  lifetime?: number | null;
}

export interface VerifyPinInput {
  operationId?: string;
  pin?: string | null;
}

export interface VerifyPinResponse {
  isSuccess?: boolean;
  errorMessage?: string | null;
}

export interface VerifyPinResponseAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: VerifyPinResponse;
}

export type OtpSendStatus = 1 | 2 | 3;

export interface OtpDto {
  operationId?: string;
  pin?: string | null;
  creationTime?: string;
  expiresOn?: string | null;
  sendTo?: string | null;
  sendType?: OtpSendType;
  recipientType?: string | null;
  recipientId?: string | null;
  actionType?: string | null;
  sentOn?: string | null;
  sendStatus?: OtpSendStatus;
  errorMessage?: string | null;
}

export interface OtpDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: OtpDto;
}

export interface OtpSettingsDto {
  passwordLength?: number;
  alphabet?: string | null;
  defaultLifetime?: number;
  ignoreOtpValidation?: boolean;
}

export interface BooleanAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: boolean;
}

export interface OtpSettingsDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: OtpSettingsDto;
}

export interface OtpSendPinQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type OtpSendPinProps = Omit<
  MutateProps<SendPinDtoAjaxResponse, AjaxResponseBase, OtpSendPinQueryParams, SendPinInput, void>,
  'path' | 'verb'
>;

export const OtpSendPin = (props: OtpSendPinProps) => (
  <Mutate<SendPinDtoAjaxResponse, AjaxResponseBase, OtpSendPinQueryParams, SendPinInput, void>
    verb="POST"
    path={`/api/services/app/Otp/SendPin`}
    {...props}
  />
);

export type UseOtpSendPinProps = Omit<
  UseMutateProps<SendPinDtoAjaxResponse, AjaxResponseBase, OtpSendPinQueryParams, SendPinInput, void>,
  'path' | 'verb'
>;

export const useOtpSendPin = (props: UseOtpSendPinProps) =>
  useMutate<SendPinDtoAjaxResponse, AjaxResponseBase, OtpSendPinQueryParams, SendPinInput, void>(
    'POST',
    `/api/services/app/Otp/SendPin`,
    props
  );

export interface OtpResendPinQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type OtpResendPinProps = Omit<
  MutateProps<SendPinDtoAjaxResponse, AjaxResponseBase, OtpResendPinQueryParams, ResendPinInput, void>,
  'path' | 'verb'
>;

export const OtpResendPin = (props: OtpResendPinProps) => (
  <Mutate<SendPinDtoAjaxResponse, AjaxResponseBase, OtpResendPinQueryParams, ResendPinInput, void>
    verb="POST"
    path={`/api/services/app/Otp/ResendPin`}
    {...props}
  />
);

export type UseOtpResendPinProps = Omit<
  UseMutateProps<SendPinDtoAjaxResponse, AjaxResponseBase, OtpResendPinQueryParams, ResendPinInput, void>,
  'path' | 'verb'
>;

export const useOtpResendPin = (props: UseOtpResendPinProps) =>
  useMutate<SendPinDtoAjaxResponse, AjaxResponseBase, OtpResendPinQueryParams, ResendPinInput, void>(
    'POST',
    `/api/services/app/Otp/ResendPin`,
    props
  );

export interface OtpVerifyPinQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type OtpVerifyPinProps = Omit<
  MutateProps<VerifyPinResponseAjaxResponse, AjaxResponseBase, OtpVerifyPinQueryParams, VerifyPinInput, void>,
  'path' | 'verb'
>;

export const OtpVerifyPin = (props: OtpVerifyPinProps) => (
  <Mutate<VerifyPinResponseAjaxResponse, AjaxResponseBase, OtpVerifyPinQueryParams, VerifyPinInput, void>
    verb="POST"
    path={`/api/services/app/Otp/VerifyPin`}
    {...props}
  />
);

export type UseOtpVerifyPinProps = Omit<
  UseMutateProps<VerifyPinResponseAjaxResponse, AjaxResponseBase, OtpVerifyPinQueryParams, VerifyPinInput, void>,
  'path' | 'verb'
>;

export const useOtpVerifyPin = (props: UseOtpVerifyPinProps) =>
  useMutate<VerifyPinResponseAjaxResponse, AjaxResponseBase, OtpVerifyPinQueryParams, VerifyPinInput, void>(
    'POST',
    `/api/services/app/Otp/VerifyPin`,
    props
  );

export interface OtpGetQueryParams {
  operationId?: string;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type OtpGetProps = Omit<GetProps<OtpDtoAjaxResponse, AjaxResponseBase, OtpGetQueryParams, void>, 'path'>;

export const OtpGet = (props: OtpGetProps) => (
  <Get<OtpDtoAjaxResponse, AjaxResponseBase, OtpGetQueryParams, void> path={`/api/services/app/Otp/Get`} {...props} />
);

export type UseOtpGetProps = Omit<UseGetProps<OtpDtoAjaxResponse, AjaxResponseBase, OtpGetQueryParams, void>, 'path'>;

export const useOtpGet = (props: UseOtpGetProps) =>
  useGet<OtpDtoAjaxResponse, AjaxResponseBase, OtpGetQueryParams, void>(`/api/services/app/Otp/Get`, props);

export interface OtpUpdateSettingsQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type OtpUpdateSettingsProps = Omit<
  MutateProps<BooleanAjaxResponse, AjaxResponseBase, OtpUpdateSettingsQueryParams, OtpSettingsDto, void>,
  'path' | 'verb'
>;

export const OtpUpdateSettings = (props: OtpUpdateSettingsProps) => (
  <Mutate<BooleanAjaxResponse, AjaxResponseBase, OtpUpdateSettingsQueryParams, OtpSettingsDto, void>
    verb="POST"
    path={`/api/services/app/Otp/UpdateSettings`}
    {...props}
  />
);

export type UseOtpUpdateSettingsProps = Omit<
  UseMutateProps<BooleanAjaxResponse, AjaxResponseBase, OtpUpdateSettingsQueryParams, OtpSettingsDto, void>,
  'path' | 'verb'
>;

export const useOtpUpdateSettings = (props: UseOtpUpdateSettingsProps) =>
  useMutate<BooleanAjaxResponse, AjaxResponseBase, OtpUpdateSettingsQueryParams, OtpSettingsDto, void>(
    'POST',
    `/api/services/app/Otp/UpdateSettings`,
    props
  );

export interface OtpGetSettingsQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type OtpGetSettingsProps = Omit<
  GetProps<OtpSettingsDtoAjaxResponse, AjaxResponseBase, OtpGetSettingsQueryParams, void>,
  'path'
>;

export const OtpGetSettings = (props: OtpGetSettingsProps) => (
  <Get<OtpSettingsDtoAjaxResponse, AjaxResponseBase, OtpGetSettingsQueryParams, void>
    path={`/api/services/app/Otp/GetSettings`}
    {...props}
  />
);

export type UseOtpGetSettingsProps = Omit<
  UseGetProps<OtpSettingsDtoAjaxResponse, AjaxResponseBase, OtpGetSettingsQueryParams, void>,
  'path'
>;

export const useOtpGetSettings = (props: UseOtpGetSettingsProps) =>
  useGet<OtpSettingsDtoAjaxResponse, AjaxResponseBase, OtpGetSettingsQueryParams, void>(
    `/api/services/app/Otp/GetSettings`,
    props
  );
