/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface ReferenceListItemValueDto {
  item?: string | null;
  itemValue?: number | null;
}

export interface OtpAuditItemDto {
  id?: string;
  creationTime?: string;
  sendTo?: string | null;
  sendType?: ReferenceListItemValueDto;
  recipientType?: string | null;
  recipientId?: string | null;
  expiresOn?: string | null;
  otp?: string | null;
  actionType?: string | null;
  sentOn?: string | null;
  sendStatus?: ReferenceListItemValueDto;
  errorMessage?: string | null;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface OtpAuditItemDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: OtpAuditItemDto;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface OtpAuditItemDtoPagedResultDto {
  items?: OtpAuditItemDto[] | null;
  totalCount?: number;
}

export interface OtpAuditItemDtoPagedResultDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: OtpAuditItemDtoPagedResultDto;
}

export interface OtpAuditItemGetQueryParams {
  id?: string;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type OtpAuditItemGetProps = Omit<
  GetProps<OtpAuditItemDtoAjaxResponse, AjaxResponseBase, OtpAuditItemGetQueryParams, void>,
  'path'
>;

export const OtpAuditItemGet = (props: OtpAuditItemGetProps) => (
  <Get<OtpAuditItemDtoAjaxResponse, AjaxResponseBase, OtpAuditItemGetQueryParams, void>
    path={`/api/services/app/OtpAuditItem/Get`}
    {...props}
  />
);

export type UseOtpAuditItemGetProps = Omit<
  UseGetProps<OtpAuditItemDtoAjaxResponse, AjaxResponseBase, OtpAuditItemGetQueryParams, void>,
  'path'
>;

export const useOtpAuditItemGet = (props: UseOtpAuditItemGetProps) =>
  useGet<OtpAuditItemDtoAjaxResponse, AjaxResponseBase, OtpAuditItemGetQueryParams, void>(
    `/api/services/app/OtpAuditItem/Get`,
    props
  );

export interface OtpAuditItemGetAllQueryParams {
  sorting?: string | null;
  skipCount?: number;
  maxResultCount?: number;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type OtpAuditItemGetAllProps = Omit<
  GetProps<OtpAuditItemDtoPagedResultDtoAjaxResponse, AjaxResponseBase, OtpAuditItemGetAllQueryParams, void>,
  'path'
>;

export const OtpAuditItemGetAll = (props: OtpAuditItemGetAllProps) => (
  <Get<OtpAuditItemDtoPagedResultDtoAjaxResponse, AjaxResponseBase, OtpAuditItemGetAllQueryParams, void>
    path={`/api/services/app/OtpAuditItem/GetAll`}
    {...props}
  />
);

export type UseOtpAuditItemGetAllProps = Omit<
  UseGetProps<OtpAuditItemDtoPagedResultDtoAjaxResponse, AjaxResponseBase, OtpAuditItemGetAllQueryParams, void>,
  'path'
>;

export const useOtpAuditItemGetAll = (props: UseOtpAuditItemGetAllProps) =>
  useGet<OtpAuditItemDtoPagedResultDtoAjaxResponse, AjaxResponseBase, OtpAuditItemGetAllQueryParams, void>(
    `/api/services/app/OtpAuditItem/GetAll`,
    props
  );

export interface OtpAuditItemCreateQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type OtpAuditItemCreateProps = Omit<
  MutateProps<OtpAuditItemDtoAjaxResponse, AjaxResponseBase, OtpAuditItemCreateQueryParams, OtpAuditItemDto, void>,
  'path' | 'verb'
>;

export const OtpAuditItemCreate = (props: OtpAuditItemCreateProps) => (
  <Mutate<OtpAuditItemDtoAjaxResponse, AjaxResponseBase, OtpAuditItemCreateQueryParams, OtpAuditItemDto, void>
    verb="POST"
    path={`/api/services/app/OtpAuditItem/Create`}
    {...props}
  />
);

export type UseOtpAuditItemCreateProps = Omit<
  UseMutateProps<OtpAuditItemDtoAjaxResponse, AjaxResponseBase, OtpAuditItemCreateQueryParams, OtpAuditItemDto, void>,
  'path' | 'verb'
>;

export const useOtpAuditItemCreate = (props: UseOtpAuditItemCreateProps) =>
  useMutate<OtpAuditItemDtoAjaxResponse, AjaxResponseBase, OtpAuditItemCreateQueryParams, OtpAuditItemDto, void>(
    'POST',
    `/api/services/app/OtpAuditItem/Create`,
    props
  );

export interface OtpAuditItemUpdateQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type OtpAuditItemUpdateProps = Omit<
  MutateProps<OtpAuditItemDtoAjaxResponse, AjaxResponseBase, OtpAuditItemUpdateQueryParams, OtpAuditItemDto, void>,
  'path' | 'verb'
>;

export const OtpAuditItemUpdate = (props: OtpAuditItemUpdateProps) => (
  <Mutate<OtpAuditItemDtoAjaxResponse, AjaxResponseBase, OtpAuditItemUpdateQueryParams, OtpAuditItemDto, void>
    verb="PUT"
    path={`/api/services/app/OtpAuditItem/Update`}
    {...props}
  />
);

export type UseOtpAuditItemUpdateProps = Omit<
  UseMutateProps<OtpAuditItemDtoAjaxResponse, AjaxResponseBase, OtpAuditItemUpdateQueryParams, OtpAuditItemDto, void>,
  'path' | 'verb'
>;

export const useOtpAuditItemUpdate = (props: UseOtpAuditItemUpdateProps) =>
  useMutate<OtpAuditItemDtoAjaxResponse, AjaxResponseBase, OtpAuditItemUpdateQueryParams, OtpAuditItemDto, void>(
    'PUT',
    `/api/services/app/OtpAuditItem/Update`,
    props
  );

export interface OtpAuditItemDeleteQueryParams {
  id?: string;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type OtpAuditItemDeleteProps = Omit<
  MutateProps<void, unknown, OtpAuditItemDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const OtpAuditItemDelete = (props: OtpAuditItemDeleteProps) => (
  <Mutate<void, unknown, OtpAuditItemDeleteQueryParams, void, void>
    verb="DELETE"
    path={`/api/services/app/OtpAuditItem/Delete`}
    {...props}
  />
);

export type UseOtpAuditItemDeleteProps = Omit<
  UseMutateProps<void, unknown, OtpAuditItemDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const useOtpAuditItemDelete = (props: UseOtpAuditItemDeleteProps) =>
  useMutate<void, unknown, OtpAuditItemDeleteQueryParams, void, void>(
    'DELETE',
    `/api/services/app/OtpAuditItem/Delete`,
    { ...props }
  );
