/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface PushSettingsDto {
  pushNotifier?: string | null;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface PushSettingsDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: PushSettingsDto;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface PushSettingsGetSettingsQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type PushSettingsGetSettingsProps = Omit<
  GetProps<PushSettingsDtoAjaxResponse, AjaxResponseBase, PushSettingsGetSettingsQueryParams, void>,
  'path'
>;

export const PushSettingsGetSettings = (props: PushSettingsGetSettingsProps) => (
  <Get<PushSettingsDtoAjaxResponse, AjaxResponseBase, PushSettingsGetSettingsQueryParams, void>
    path={`/api/Push/Settings`}
    {...props}
  />
);

export type UsePushSettingsGetSettingsProps = Omit<
  UseGetProps<PushSettingsDtoAjaxResponse, AjaxResponseBase, PushSettingsGetSettingsQueryParams, void>,
  'path'
>;

export const usePushSettingsGetSettings = (props: UsePushSettingsGetSettingsProps) =>
  useGet<PushSettingsDtoAjaxResponse, AjaxResponseBase, PushSettingsGetSettingsQueryParams, void>(
    `/api/Push/Settings`,
    props
  );

export interface PushSettingsUpdateSettingsQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type PushSettingsUpdateSettingsProps = Omit<
  MutateProps<void, unknown, PushSettingsUpdateSettingsQueryParams, PushSettingsDto, void>,
  'path' | 'verb'
>;

export const PushSettingsUpdateSettings = (props: PushSettingsUpdateSettingsProps) => (
  <Mutate<void, unknown, PushSettingsUpdateSettingsQueryParams, PushSettingsDto, void>
    verb="PUT"
    path={`/api/Push/Settings`}
    {...props}
  />
);

export type UsePushSettingsUpdateSettingsProps = Omit<
  UseMutateProps<void, unknown, PushSettingsUpdateSettingsQueryParams, PushSettingsDto, void>,
  'path' | 'verb'
>;

export const usePushSettingsUpdateSettings = (props: UsePushSettingsUpdateSettingsProps) =>
  useMutate<void, unknown, PushSettingsUpdateSettingsQueryParams, PushSettingsDto, void>(
    'PUT',
    `/api/Push/Settings`,
    props
  );
