/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface GuidNullableEntityWithDisplayNameDto {
  id?: string | null;
  displayText?: string | null;
}

export interface ReferenceListItemDto {
  id?: string;
  item?: string | null;
  itemValue?: number;
  description?: string | null;
  orderIndex?: number;
  referenceList?: GuidNullableEntityWithDisplayNameDto;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface ReferenceListItemDtoListAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: ReferenceListItemDto[] | null;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface ReferenceListDto {
  id?: string;
  name?: string | null;
  description?: string | null;
  hardLinkToApplication?: boolean;
  namespace?: string | null;
  noSelectionValue?: number | null;
}

export interface ReferenceListDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: ReferenceListDto;
}

export interface ReferenceListDtoPagedResultDto {
  items?: ReferenceListDto[] | null;
  totalCount?: number;
}

export interface ReferenceListDtoPagedResultDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: ReferenceListDtoPagedResultDto;
}

export interface ReferenceListGetItemsQueryParams {
  namespace?: string | null;
  name?: string | null;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type ReferenceListGetItemsProps = Omit<
  GetProps<ReferenceListItemDtoListAjaxResponse, AjaxResponseBase, ReferenceListGetItemsQueryParams, void>,
  'path'
>;

export const ReferenceListGetItems = (props: ReferenceListGetItemsProps) => (
  <Get<ReferenceListItemDtoListAjaxResponse, AjaxResponseBase, ReferenceListGetItemsQueryParams, void>
    path={`/api/services/app/ReferenceList/GetItems`}
    {...props}
  />
);

export type UseReferenceListGetItemsProps = Omit<
  UseGetProps<ReferenceListItemDtoListAjaxResponse, AjaxResponseBase, ReferenceListGetItemsQueryParams, void>,
  'path'
>;

export const useReferenceListGetItems = (props: UseReferenceListGetItemsProps) =>
  useGet<ReferenceListItemDtoListAjaxResponse, AjaxResponseBase, ReferenceListGetItemsQueryParams, void>(
    `/api/services/app/ReferenceList/GetItems`,
    props
  );

export interface ReferenceListGetQueryParams {
  id?: string;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type ReferenceListGetProps = Omit<
  GetProps<ReferenceListDtoAjaxResponse, AjaxResponseBase, ReferenceListGetQueryParams, void>,
  'path'
>;

export const ReferenceListGet = (props: ReferenceListGetProps) => (
  <Get<ReferenceListDtoAjaxResponse, AjaxResponseBase, ReferenceListGetQueryParams, void>
    path={`/api/services/app/ReferenceList/Get`}
    {...props}
  />
);

export type UseReferenceListGetProps = Omit<
  UseGetProps<ReferenceListDtoAjaxResponse, AjaxResponseBase, ReferenceListGetQueryParams, void>,
  'path'
>;

export const useReferenceListGet = (props: UseReferenceListGetProps) =>
  useGet<ReferenceListDtoAjaxResponse, AjaxResponseBase, ReferenceListGetQueryParams, void>(
    `/api/services/app/ReferenceList/Get`,
    props
  );

export interface ReferenceListGetAllQueryParams {
  sorting?: string | null;
  skipCount?: number;
  maxResultCount?: number;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type ReferenceListGetAllProps = Omit<
  GetProps<ReferenceListDtoPagedResultDtoAjaxResponse, AjaxResponseBase, ReferenceListGetAllQueryParams, void>,
  'path'
>;

export const ReferenceListGetAll = (props: ReferenceListGetAllProps) => (
  <Get<ReferenceListDtoPagedResultDtoAjaxResponse, AjaxResponseBase, ReferenceListGetAllQueryParams, void>
    path={`/api/services/app/ReferenceList/GetAll`}
    {...props}
  />
);

export type UseReferenceListGetAllProps = Omit<
  UseGetProps<ReferenceListDtoPagedResultDtoAjaxResponse, AjaxResponseBase, ReferenceListGetAllQueryParams, void>,
  'path'
>;

export const useReferenceListGetAll = (props: UseReferenceListGetAllProps) =>
  useGet<ReferenceListDtoPagedResultDtoAjaxResponse, AjaxResponseBase, ReferenceListGetAllQueryParams, void>(
    `/api/services/app/ReferenceList/GetAll`,
    props
  );

export interface ReferenceListCreateQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type ReferenceListCreateProps = Omit<
  MutateProps<ReferenceListDtoAjaxResponse, AjaxResponseBase, ReferenceListCreateQueryParams, ReferenceListDto, void>,
  'path' | 'verb'
>;

export const ReferenceListCreate = (props: ReferenceListCreateProps) => (
  <Mutate<ReferenceListDtoAjaxResponse, AjaxResponseBase, ReferenceListCreateQueryParams, ReferenceListDto, void>
    verb="POST"
    path={`/api/services/app/ReferenceList/Create`}
    {...props}
  />
);

export type UseReferenceListCreateProps = Omit<
  UseMutateProps<
    ReferenceListDtoAjaxResponse,
    AjaxResponseBase,
    ReferenceListCreateQueryParams,
    ReferenceListDto,
    void
  >,
  'path' | 'verb'
>;

export const useReferenceListCreate = (props: UseReferenceListCreateProps) =>
  useMutate<ReferenceListDtoAjaxResponse, AjaxResponseBase, ReferenceListCreateQueryParams, ReferenceListDto, void>(
    'POST',
    `/api/services/app/ReferenceList/Create`,
    props
  );

export interface ReferenceListUpdateQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type ReferenceListUpdateProps = Omit<
  MutateProps<ReferenceListDtoAjaxResponse, AjaxResponseBase, ReferenceListUpdateQueryParams, ReferenceListDto, void>,
  'path' | 'verb'
>;

export const ReferenceListUpdate = (props: ReferenceListUpdateProps) => (
  <Mutate<ReferenceListDtoAjaxResponse, AjaxResponseBase, ReferenceListUpdateQueryParams, ReferenceListDto, void>
    verb="PUT"
    path={`/api/services/app/ReferenceList/Update`}
    {...props}
  />
);

export type UseReferenceListUpdateProps = Omit<
  UseMutateProps<
    ReferenceListDtoAjaxResponse,
    AjaxResponseBase,
    ReferenceListUpdateQueryParams,
    ReferenceListDto,
    void
  >,
  'path' | 'verb'
>;

export const useReferenceListUpdate = (props: UseReferenceListUpdateProps) =>
  useMutate<ReferenceListDtoAjaxResponse, AjaxResponseBase, ReferenceListUpdateQueryParams, ReferenceListDto, void>(
    'PUT',
    `/api/services/app/ReferenceList/Update`,
    props
  );

export interface ReferenceListDeleteQueryParams {
  id?: string;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type ReferenceListDeleteProps = Omit<
  MutateProps<void, unknown, ReferenceListDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const ReferenceListDelete = (props: ReferenceListDeleteProps) => (
  <Mutate<void, unknown, ReferenceListDeleteQueryParams, void, void>
    verb="DELETE"
    path={`/api/services/app/ReferenceList/Delete`}
    {...props}
  />
);

export type UseReferenceListDeleteProps = Omit<
  UseMutateProps<void, unknown, ReferenceListDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const useReferenceListDelete = (props: UseReferenceListDeleteProps) =>
  useMutate<void, unknown, ReferenceListDeleteQueryParams, void, void>(
    'DELETE',
    `/api/services/app/ReferenceList/Delete`,
    { ...props }
  );
