/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface SmsPortalSettingsDto {
  host?: string | null;
  username?: string | null;
  password?: string | null;
  useProxy?: boolean;
  webProxyAddress?: string | null;
  useDefaultProxyCredentials?: boolean;
  webProxyUsername?: string | null;
  webProxyPassword?: string | null;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface BooleanAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: boolean;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface SmsPortalSettingsDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: SmsPortalSettingsDto;
}

export interface SmsPortalUpdateSettingsQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type SmsPortalUpdateSettingsProps = Omit<
  MutateProps<BooleanAjaxResponse, AjaxResponseBase, SmsPortalUpdateSettingsQueryParams, SmsPortalSettingsDto, void>,
  'path' | 'verb'
>;

export const SmsPortalUpdateSettings = (props: SmsPortalUpdateSettingsProps) => (
  <Mutate<BooleanAjaxResponse, AjaxResponseBase, SmsPortalUpdateSettingsQueryParams, SmsPortalSettingsDto, void>
    verb="PUT"
    path={`/api/SmsPortal/Settings`}
    {...props}
  />
);

export type UseSmsPortalUpdateSettingsProps = Omit<
  UseMutateProps<BooleanAjaxResponse, AjaxResponseBase, SmsPortalUpdateSettingsQueryParams, SmsPortalSettingsDto, void>,
  'path' | 'verb'
>;

export const useSmsPortalUpdateSettings = (props: UseSmsPortalUpdateSettingsProps) =>
  useMutate<BooleanAjaxResponse, AjaxResponseBase, SmsPortalUpdateSettingsQueryParams, SmsPortalSettingsDto, void>(
    'PUT',
    `/api/SmsPortal/Settings`,
    props
  );

export interface SmsPortalGetSettingsQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type SmsPortalGetSettingsProps = Omit<
  GetProps<SmsPortalSettingsDtoAjaxResponse, AjaxResponseBase, SmsPortalGetSettingsQueryParams, void>,
  'path'
>;

export const SmsPortalGetSettings = (props: SmsPortalGetSettingsProps) => (
  <Get<SmsPortalSettingsDtoAjaxResponse, AjaxResponseBase, SmsPortalGetSettingsQueryParams, void>
    path={`/api/SmsPortal/Settings`}
    {...props}
  />
);

export type UseSmsPortalGetSettingsProps = Omit<
  UseGetProps<SmsPortalSettingsDtoAjaxResponse, AjaxResponseBase, SmsPortalGetSettingsQueryParams, void>,
  'path'
>;

export const useSmsPortalGetSettings = (props: UseSmsPortalGetSettingsProps) =>
  useGet<SmsPortalSettingsDtoAjaxResponse, AjaxResponseBase, SmsPortalGetSettingsQueryParams, void>(
    `/api/SmsPortal/Settings`,
    props
  );
