export const FILLED_ICON_GROUPS = {
  directional: [
    'StepForwardFilled',
    'FastBackwardFilled',
    'FastForwardFilled',
    'CaretUpFilled',
    'CaretDownFilled',
    'CaretLeftFilled',
    'CaretRightFilled',
    'UpCircleFilled',
    'DownCircleFilled',
    'LeftCircleFilled',
    'RightCircleFilled',
    'ForwardFilled',
    'BackwardFilled',
    'PlayCircleFilled',
    'UpSquareFilled',
    'DownSquareFilled',
    'LeftSquareFilled',
    'RightSquareFilled',
  ] as const,
  suggested: [
    'QuestionCircleFilled',
    'PauseCircleFilled',
    'MinusCircleFilled',
    'PlusSquareFilled',
    'MinusSquareFilled',
    'InfoCircleFilled',
    'ExclamationCircleFilled',
    'CloseCircleFilled',
    'CloseSquareFilled',
    'CheckCircleFilled',
    'CheckSquareFilled',
    'ClockCircleFilled',
    'WarningFilled',
    'StopFilled',
  ] as const,
  editor: ['EditFilled', 'CopyFilled', 'DeleteFilled', 'SnippetsFilled', 'DiffFilled', 'HighlightFilled'] as const,
  data: ['PieChartFilled', 'BoxPlotFilled', 'FundFilled', 'SlidersFilled'] as const,
  brandAndLogos: [
    'AndroidFilled',
    'AppleFilled',
    'WindowsFilled',
    'ChromeFilled',
    'GithubFilled',
    'AliwangwangFilled',
    'WeiboSquareFilled',
    'WeiboCircleFilled',
    'TaobaoCircleFilled',
    'Html5Filled',
    'WechatFilled',
    'YoutubeFilled',
    'AlipayCircleFilled',
    'SkypeFilled',
    'GitlabFilled',
    'LinkedinFilled',
    'FacebookFilled',
    'CodeSandboxCircleFilled',
    'CodepenCircleFilled',
    'SlackSquareFilled',
    'BehanceSquareFilled',
    'DribbbleSquareFilled',
    'InstagramFilled',
    'YuqueFilled',
    'YahooFilled',
  ] as const,
  application: [
    'AccountBookFilled',
    'AlertFilled',
    'AlipaySquareFilled',
    'AmazonCircleFilled',
    'AmazonSquareFilled',
    'ApiFilled',
    'AppstoreFilled',
    'AudioFilled',
    'BankFilled',
    'BehanceCircleFilled',
    'BellFilled',
    'BookFilled',
    'BugFilled',
    'BuildFilled',
    'BulbFilled',
    'CalculatorFilled',
    'CalendarFilled',
    'CameraFilled',
    'CarFilled',
    'CarryOutFilled',
    'CiCircleFilled',
    'CloudFilled',
    'CodeFilled',
    'CodeSandboxSquareFilled',
    'CodepenSquareFilled',
    'CompassFilled',
    'ContactsFilled',
    'ContainerFilled',
    'ControlFilled',
    'CreditCardFilled',
    'CrownFilled',
    'CustomerServiceFilled',
    'DashboardFilled',
    'DatabaseFilled',
    'DingtalkCircleFilled',
    'DingtalkSquareFilled',
    'DislikeFilled',
    'DollarCircleFilled',
    'DribbbleCircleFilled',
    'DropboxCircleFilled',
    'DropboxSquareFilled',
    'EnvironmentFilled',
    'EuroCircleFilled',
    'ExperimentFilled',
    'EyeFilled',
    'EyeInvisibleFilled',
    'FileAddFilled',
    'FileExcelFilled',
    'FileExclamationFilled',
    'FileFilled',
    'FileImageFilled',
    'FileMarkdownFilled',
    'FilePdfFilled',
    'FilePptFilled',
    'FileTextFilled',
    'FileUnknownFilled',
    'FileWordFilled',
    'FileZipFilled',
    'FilterFilled',
    'FireFilled',
    'FlagFilled',
    'FolderAddFilled',
    'FolderFilled',
    'FolderOpenFilled',
    'FormatPainterFilled',
    'FrownFilled',
    'FunnelPlotFilled',
    'GiftFilled',
    'GoldFilled',
    'GoldenFilled',
    'GoogleCircleFilled',
    'GooglePlusCircleFilled',
    'GooglePlusSquareFilled',
    'GoogleSquareFilled',
    'HddFilled',
    'HeartFilled',
    'HomeFilled',
    'HourglassFilled',
    'IdcardFilled',
    'IeCircleFilled',
    'IeSquareFilled',
    'InsuranceFilled',
    'InteractionFilled',
    'LayoutFilled',
    'LikeFilled',
    'LockFilled',
    'MacCommandFilled',
    'MailFilled',
    'MedicineBoxFilled',
    'MediumCircleFilled',
    'MediumSquareFilled',
    'MehFilled',
    'MessageFilled',
    'MobileFilled',
    'MoneyCollectFilled',
    'NotificationFilled',
    'PayCircleFilled',
    'PhoneFilled',
    'PictureFilled',
    'PlaySquareFilled',
    'PoundCircleFilled',
    'PrinterFilled',
    'ProfileFilled',
    'ProjectFilled',
    'PropertySafetyFilled',
    'PushpinFilled',
    'QqCircleFilled',
    'QqSquareFilled',
    'ReadFilled',
    'ReconciliationFilled',
    'RedEnvelopeFilled',
    'RedditCircleFilled',
    'RedditSquareFilled',
    'RestFilled',
    'RobotFilled',
    'RocketFilled',
    'SafetyCertificateFilled',
    'SaveFilled',
    'ScheduleFilled',
    'SecurityScanFilled',
    'SettingFilled',
    'ShopFilled',
    'ShoppingFilled',
    'SignalFilled',
    'SketchCircleFilled',
    'SketchSquareFilled',
    'SkinFilled',
    'SlackCircleFilled',
    'SmileFilled',
    'SoundFilled',
    'StarFilled',
    'SwitcherFilled',
    'TabletFilled',
    'TagFilled',
    'TagsFilled',
    'TaobaoSquareFilled',
    'ThunderboltFilled',
    'ToolFilled',
    'TrademarkCircleFilled',
    'TrophyFilled',
    'TwitterCircleFilled',
    'TwitterSquareFilled',
    'UnlockFilled',
    'UsbFilled',
    'VideoCameraFilled',
    'WalletFilled',
    'ZhihuCircleFilled',
    'ZhihuSquareFilled',
  ] as const,
};

export type DirectionalFilledIconTypes = typeof FILLED_ICON_GROUPS.directional[number];

export type SuggestedFilledIconTypes = typeof FILLED_ICON_GROUPS.suggested[number];

export type EditorFilledIconTypes = typeof FILLED_ICON_GROUPS.editor[number];

export type DataFilledIconTypes = typeof FILLED_ICON_GROUPS.data[number];

export type BrandAndLogosFilledIconTypes = typeof FILLED_ICON_GROUPS.brandAndLogos[number];

export type ApplicationFilledIconTypes = typeof FILLED_ICON_GROUPS.application[number];

export type FilledIconTypes =
  | DirectionalFilledIconTypes |
  SuggestedFilledIconTypes |
  EditorFilledIconTypes |
  DataFilledIconTypes |
  BrandAndLogosFilledIconTypes |
  ApplicationFilledIconTypes;
