export const TWO_FACED_ICON_GROUPS = {
  directional: [
    'UpCircleTwoTone',
    'DownCircleTwoTone',
    'LeftCircleTwoTone',
    'RightCircleTwoTone',
    'PlayCircleTwoTone',
    'UpSquareTwoTone',
    'DownSquareTwoTone',
    'LeftSquareTwoTone',
    'RightSquareTwoTone',
  ] as const,
  suggested: [
    'QuestionCircleTwoTone',
    'PlusCircleTwoTone',
    'PauseCircleTwoTone',
    'MinusCircleTwoTone',
    'PlusSquareTwoTone',
    'MinusSquareTwoTone',
    'InfoCircleTwoTone',
    'ExclamationCircleTwoTone',
    'CloseCircleTwoTone',
    'CloseSquareTwoTone',
    'CheckCircleTwoTone',
    'CheckSquareTwoTone',
    'ClockCircleTwoTone',
    'WarningTwoTone',
    'StopTwoTone',
  ] as const,
  editor: [
    'EditTwoTone',
    'CopyTwoTone',
    'DeleteTwoTone',
    'SnippetsTwoTone',
    'DiffTwoTone',
    'HighlightTwoTone',
  ] as const,
  data: ['PieChartTwoTone', 'BoxPlotTwoTone', 'FundTwoTone', 'SlidersTwoTone'] as const,
  brandAndLogos: ['Html5TwoTone'] as const,
  application: [
    'AccountBookTwoTone',
    'AlertTwoTone',
    'ApiTwoTone',
    'AppstoreTwoTone',
    'AudioTwoTone',
    'BankTwoTone',
    'BellTwoTone',
    'BookTwoTone',
    'BugTwoTone',
    'BuildTwoTone',
    'BulbTwoTone',
    'CalculatorTwoTone',
    'CalendarTwoTone',
    'CameraTwoTone',
    'CarTwoTone',
    'CarryOutTwoTone',
    'CiCircleTwoTone',
    'CiTwoTone',
    'CloudTwoTone',
    'CodeTwoTone',
    'CompassTwoTone',
    'ContactsTwoTone',
    'ContainerTwoTone',
    'ControlTwoTone',
    'CopyrightTwoTone',
    'CreditCardTwoTone',
    'CrownTwoTone',
    'CustomerServiceTwoTone',
    'DashboardTwoTone',
    'DatabaseTwoTone',
    'DislikeTwoTone',
    'DollarCircleTwoTone',
    'DollarTwoTone',
    'EnvironmentTwoTone',
    'EuroCircleTwoTone',
    'EuroTwoTone',
    'ExperimentTwoTone',
    'EyeTwoTone',
    'EyeInvisibleTwoTone',
    'FileAddTwoTone',
    'FileExcelTwoTone',
    'FileExclamationTwoTone',
    'FileTwoTone',
    'FileImageTwoTone',
    'FileMarkdownTwoTone',
    'FilePdfTwoTone',
    'FilePptTwoTone',
    'FileTextTwoTone',
    'FileUnknownTwoTone',
    'FileWordTwoTone',
    'FileZipTwoTone',
    'FilterTwoTone',
    'FireTwoTone',
    'FlagTwoTone',
    'FolderAddTwoTone',
    'FolderTwoTone',
    'FolderOpenTwoTone',
    'FrownTwoTone',
    'FunnelPlotTwoTone',
    'GiftTwoTone',
    'GoldTwoTone',
    'HddTwoTone',
    'HeartTwoTone',
    'HomeTwoTone',
    'HourglassTwoTone',
    'IdcardTwoTone',
    'InsuranceTwoTone',
    'InteractionTwoTone',
    'LayoutTwoTone',
    'LikeTwoTone',
    'LockTwoTone',
    'MailTwoTone',
    'MedicineBoxTwoTone',
    'MehTwoTone',
    'MessageTwoTone',
    'MobileTwoTone',
    'MoneyCollectTwoTone',
    'NotificationTwoTone',
    'PhoneTwoTone',
    'PictureTwoTone',
    'PlaySquareTwoTone',
    'PoundCircleTwoTone',
    'PrinterTwoTone',
    'ProfileTwoTone',
    'ProjectTwoTone',
    'PropertySafetyTwoTone',
    'PushpinTwoTone',
    'ReconciliationTwoTone',
    'RedEnvelopeTwoTone',
    'RestTwoTone',
    'RocketTwoTone',
    'SafetyCertificateTwoTone',
    'SaveTwoTone',
    'ScheduleTwoTone',
    'SecurityScanTwoTone',
    'SettingTwoTone',
    'ShopTwoTone',
    'ShoppingTwoTone',
    'SkinTwoTone',
    'SmileTwoTone',
    'SoundTwoTone',
    'StarTwoTone',
    'SwitcherTwoTone',
    'TabletTwoTone',
    'TagTwoTone',
    'TagsTwoTone',
    'ThunderboltTwoTone',
    'ToolTwoTone',
    'TrademarkCircleTwoTone',
    'TrophyTwoTone',
    'UnlockTwoTone',
    'UsbTwoTone',
    'VideoCameraTwoTone',
    'WalletTwoTone',
  ] as const,
};

export type DirectionalTwoToneIconTypes = typeof TWO_FACED_ICON_GROUPS.directional[number];

export type SuggestedTwoToneIconTypes = typeof TWO_FACED_ICON_GROUPS.suggested[number];

export type EditorTwoToneIconTypes = typeof TWO_FACED_ICON_GROUPS.editor[number];

export type DataTwoToneIconTypes = typeof TWO_FACED_ICON_GROUPS.data[number];

export type BrandAndLogosTwoToneIconTypes = typeof TWO_FACED_ICON_GROUPS.brandAndLogos[number];

export type ApplicationTwoToneIconTypes = typeof TWO_FACED_ICON_GROUPS.application[number];

export type TwoToneIconTypes =
  | DirectionalTwoToneIconTypes |
  SuggestedTwoToneIconTypes |
  EditorTwoToneIconTypes |
  DataTwoToneIconTypes |
  BrandAndLogosTwoToneIconTypes |
  ApplicationTwoToneIconTypes;
