trigger:
  branches:
    include:
    - refs/heads/main
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Test
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    submodules: true
    persistCredentials: True
  - task: NodeTool@0
    displayName: Use Node 12.18.3
    inputs:
      versionSpec: 12.18.3
  - task: PowerShell@2
    displayName: Environment Variables
    inputs:
      targetType: inline
      script: >-
        # Create local environments

        New-Item .env.local

        New-Item .env


        # Set Base Url

        Set-Content .env.local "BASE_URL=${Env:BASE_URL}"

        Set-Content .env "BASE_URL=${Env:BASE_URL}"


        # Set Google Maps API Key

        Add-Content .env.local "GOOGLE_MAPS_API_KEY="

        Add-Content .env "GOOGLE_MAPS_API_KEY="


        # Set App Insights Instrumentation key

        Add-Content .env.local "APP_INSIGHTS_INSTRUMENTATION_KEY="

        Add-Content .env "APP_INSIGHTS_INSTRUMENTATION_KEY="


        ########## BROWSER ############


        # Set Base Url

        Add-Content .env.local "NEXT_PUBLIC_BASE_URL=$BASE_URL"

        Add-Content .env "NEXT_PUBLIC_BASE_URL=$BASE_URL"


        # Set Google Maps API Key

        Add-Content .env.local "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY"

        Add-Content .env "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY"


        # Set App Insights Instrumentation key

        Add-Content .env.local "NEXT_PUBLIC_APP_INSIGHTS_INSTRUMENTATION_KEY=$APP_INSIGHTS_INSTRUMENTATION_KEY"

        Add-Content .env "NEXT_PUBLIC_APP_INSIGHTS_INSTRUMENTATION_KEY=$APP_INSIGHTS_INSTRUMENTATION_KEY"
  - task: PowerShell@2
    displayName: Update Web Config
    inputs:
      targetType: inline
      script: >-
        # Update Web Config

        Set-Content public/static/config/web.config.js "if (typeof window) { window.__APP_CONFIG__ = { appInsightsInstrumentationKey: null, baseUrl: '${Env:BASE_URL}', googleMapsApiKey: null, };}"
  - task: Npm@1
    displayName: Npm Install
    inputs:
      verbose: false
  - task: Npm@1
    displayName: Install Latest Shesha
    inputs:
      command: custom
      verbose: false
      customCommand: install @shesha-io/reactjs@latest
  - task: Npm@1
    displayName: Npm Build
    inputs:
      command: custom
      verbose: true
      customCommand: run build
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/shesha-fe-test.zip'
      replaceExistingArchive: true  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: shesha-fe-test'
    inputs:
      ArtifactName: shesha-fe
- job: Job_2
  displayName: Qa
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    submodules: true
  - task: NodeTool@0
    displayName: Use Node 12.18.3
    inputs:
      versionSpec: 12.18.3
  - task: PowerShell@2
    displayName: Environment Variables
    inputs:
      targetType: inline
      script: >-
        # Create local environments

        New-Item .env.local

        New-Item .env


        # Set Base Url

        Set-Content .env.local "BASE_URL=${Env:BASE_URL}"

        Set-Content .env "BASE_URL=${Env:BASE_URL}"


        # Set Google Maps API Key

        Add-Content .env.local "GOOGLE_MAPS_API_KEY="

        Add-Content .env "GOOGLE_MAPS_API_KEY="


        # Set App Insights Instrumentation key

        Add-Content .env.local "APP_INSIGHTS_INSTRUMENTATION_KEY="

        Add-Content .env "APP_INSIGHTS_INSTRUMENTATION_KEY="


        ########## BROWSER ############


        # Set Base Url

        Add-Content .env.local "NEXT_PUBLIC_BASE_URL=$BASE_URL"

        Add-Content .env "NEXT_PUBLIC_BASE_URL=$BASE_URL"


        # Set Google Maps API Key

        Add-Content .env.local "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY"

        Add-Content .env "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY"


        # Set App Insights Instrumentation key

        Add-Content .env.local "NEXT_PUBLIC_APP_INSIGHTS_INSTRUMENTATION_KEY=$APP_INSIGHTS_INSTRUMENTATION_KEY"

        Add-Content .env "NEXT_PUBLIC_APP_INSIGHTS_INSTRUMENTATION_KEY=$APP_INSIGHTS_INSTRUMENTATION_KEY"
  - task: PowerShell@2
    displayName: Update Web Config
    inputs:
      targetType: inline
      script: >-
        # Update Web Config

        Set-Content public/static/config/web.config.js "if (typeof window) { window.__APP_CONFIG__ = { appInsightsInstrumentationKey: null, baseUrl: '${Env:BASE_URL}', googleMapsApiKey: null, };}"
  - task: Npm@1
    displayName: Npm Install
    inputs:
      verbose: false
  - task: Npm@1
    displayName: Install Latest Shesha
    inputs:
      command: custom
      verbose: false
      customCommand: install @shesha-io/reactjs@latest
  - task: Npm@1
    displayName: Npm Build
    inputs:
      command: custom
      verbose: true
      customCommand: run build
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/shesha-fe-qa.zip'
      replaceExistingArchive: true       
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: shesha-fe-qa'
    inputs:
      ArtifactName: shesha-fe
- job: Job_3
  displayName: Production
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    submodules: true
  - task: NodeTool@0
    displayName: Use Node 12.18.3
    inputs:
      versionSpec: 12.18.3
  - task: PowerShell@2
    displayName: Environment Variables
    inputs:
      targetType: inline
      script: >-
        # Create local environments

        New-Item .env.local

        New-Item .env


        # Set Base Url

        Set-Content .env.local "BASE_URL=${Env:BASE_URL}"

        Set-Content .env "BASE_URL=${Env:BASE_URL}"


        # Set Google Maps API Key

        Add-Content .env.local "GOOGLE_MAPS_API_KEY="

        Add-Content .env "GOOGLE_MAPS_API_KEY="


        # Set App Insights Instrumentation key

        Add-Content .env.local "APP_INSIGHTS_INSTRUMENTATION_KEY="

        Add-Content .env "APP_INSIGHTS_INSTRUMENTATION_KEY="


        ########## BROWSER ############


        # Set Base Url

        Add-Content .env.local "NEXT_PUBLIC_BASE_URL=$BASE_URL"

        Add-Content .env "NEXT_PUBLIC_BASE_URL=$BASE_URL"


        # Set Google Maps API Key

        Add-Content .env.local "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY"

        Add-Content .env "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY"


        # Set App Insights Instrumentation key

        Add-Content .env.local "NEXT_PUBLIC_APP_INSIGHTS_INSTRUMENTATION_KEY=$APP_INSIGHTS_INSTRUMENTATION_KEY"

        Add-Content .env "NEXT_PUBLIC_APP_INSIGHTS_INSTRUMENTATION_KEY=$APP_INSIGHTS_INSTRUMENTATION_KEY"
  - task: PowerShell@2
    displayName: Update Web Config
    inputs:
      targetType: inline
      script: >-
        # Update Web Config

        Set-Content public/static/config/web.config.js "if (typeof window) { window.__APP_CONFIG__ = { appInsightsInstrumentationKey: null, baseUrl: '${Env:BASE_URL}', googleMapsApiKey: null, };}"
  - task: Npm@1
    displayName: Npm Install
    inputs:
      verbose: false
  - task: Npm@1
    displayName: Install Latest Shesha
    inputs:
      command: custom
      verbose: false
      customCommand: install @shesha-io/reactjs@latest
  - task: Npm@1
    displayName: Npm Build
    inputs:
      command: custom
      verbose: true
      customCommand: run build
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/shesha-fe-prod.zip'      
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: shesha-fe-prod'
    inputs:
      ArtifactName: shesha-fe
...