name: tag-shesha

# This workflow is designed to build the shesha-core and shesha-reactjs applications 
# and then publish them to their respective repositories i.e. nuget and npmjs

# IMPORTANT!!!!!!
# we are triggering on push because branch protection and codeowners enforce 
# using pull requests to commit to the main branch

on:
  push:
    branches:
      - 'releases/**'
env:
  NODE_VERSION: '15'
  PYTHON_VERSOIN: '2.7.18'
  DOTNET_VERSION: '6.x'
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:

      # ============ CHECKOUT CODE ===============

      # checkout latest code
      - name: Get Sources
        uses: actions/checkout@v3
        run: echo "${GITHUB_REF#refs/heads/}.$(git rev-parse --short "$GITHUB_SHA")"
        with:
          clean: true

      # # ============ TAG BRANCH ===============

      # # Create Tag
      # - name: Bump version and push tag
      #   id: tag_version
      #   uses: mathieudutour/github-tag-action@v6.1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     tag_prefix: ''
      #     release_branches: ''

      # # ============ SETUP ENVIRONMENTS ===============

      # # Setup Node for shesha-reactjs
      # - name: Setup Node ${{ env.NODE_VERSION }}
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ env.NODE_VERSION }}
      #     registry-url: 'https://registry.npmjs.org'
      # # Setup Python for for shesha-reactjs (solution currently needs python2 to run)
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: ${{ env.PYTHON_VERSOIN }}
      # # Setup DOTNET for shesha-core
      # - name: Use .NET Core SDK ${{ env.DOTNET_VERSION }}
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: ${{ env.DOTNET_VERSION }}
      
      # # ============ RESOLVE DEPENDENCIES ===============

      # # DOTNET restore for shesha-core
      # - name: Dotnet Restore
      #   run: dotnet restore --configfile .nuget/NuGet.Config --verbosity detailed
      #   working-directory: ./shesha-core
      # # Install dependencies for shesha-reactjs
      # - name: Install Dependencies
      #   run: npm install --legacy-peer-deps
      #   working-directory: ./shesha-reactjs

      # # ============ METADATA ===============

      # # Update package.json tag
      # - name: Update package.json
      #   uses: reedyuk/npm-version@1.1.1
      #   with:
      #     version: ${{ steps.tag_version.outputs.new_tag }}
      #     package: 'shesha-reactjs/'
      
      # # ============ BUILD ===============

      # # Build shesha-core (Solution) for production
      # - name: Dotnet Build
      #   run: dotnet build --configuration Release
      #   working-directory: ./shesha-core
      # # Build shesha-reactjs for production
      # - name: Build shesha-reactjs for Production
      #   run: npm run build
      #   working-directory: ./shesha-reactjs

      # # ============ PACK ===============

      # # Pack shesha-core (Solution)
      # - name: Dotnet Pack shesha-core
      #   run: dotnet pack -o ../dist -p:PackageVersion=${{ steps.tag_version.outputs.new_tag }} -p:Version=${{ steps.tag_version.outputs.new_tag }} --include-symbols --include-source
      #   working-directory: ./shesha-core

      # # ============ RELEASE ===============

      # # create github release
      # - name: Create Github Release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     tag: ${{ steps.tag_version.outputs.new_tag }}
      #     name: shesha-reactjs@${{ steps.tag_version.outputs.new_tag }}
      #     body: ${{ steps.tag_version.outputs.changelog }}